apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-jaeger 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: linkerd-jaeger
    repoURL: https://helm.linkerd.io/stable 
    targetRevision: 30.12.11
    helm:
      releaseName: linkerd-jaeger
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkerd-jaeger
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
