apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ripe-atlas
  name: ripe-atlas
  namespace: ripe-atlas
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ripe-atlas
  template:
    metadata:
      labels:
        app: ripe-atlas
    spec:
      containers:
        - image: jamesits/ripe-atlas:latest
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["CHOWN", "SETUID", "SETGID", "DAC_OVERRIDE", "NET_RAW"]
          env:
          - name: RXTXRPT 
            value: "yes"
          imagePullPolicy: Always
          name: ripe-atlas
          volumeMounts:
            - name: ripe-atlas-key
              mountPath: "/var/atlas-probe/etc/probe_key"
              subPath: probe_key
              readOnly: false
            - name: ripe-atlas-key
              mountPath: "/var/atlas-probe/etc/probe_key.pub"
              readOnly: false
              subPath: probe_key.pub
            - name: atlas-ripe-status
              mountPath: "/var/atlas-probe/status"
      restartPolicy: Always
      volumes:
        - name: atlas-ripe-status
          persistentVolumeClaim:
            claimName: atlas-ripe-status
        - name: ripe-atlas-key
          secret:
            secretName: ripe-atlas
