kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: atlas-ripe-status
  namespace: ripe-atlas
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
