apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  project: default
  source:
    chart: crossplane-stable
    repoURL: https://charts.crossplane.io/stable 
    targetRevision: 1.15.2
    helm:
      releaseName: crossplane
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m   
