apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: crossplane
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable 
    targetRevision: 1.15.2
    helm:
      releaseName: crossplane
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
