apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts 
    targetRevision: 4.5.2
    helm:
      releaseName: falcosecurity
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
