apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io 
    targetRevision: 1.14.2
    helm:
      releaseName: harbor
      values: |
        expose:
          type: nodePort
          tls:
            auto:
              commonName: harbor
          #ingress:
          #  hosts:
          #    core: core.harbor.domain
          #    notary: notary.harbor.domain
        #externalURL: https://core.harbor.domain
  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
