apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-secrets 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: "helmcharts/linkerd-secrets" 
    repoURL: "git@github.com:p-bogdan/argocd-charts.git" 
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
