apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ripe-atlas 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ripe-atlas
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helmcharts/ripe-atlas
    repoURL: "git@github.com:p-bogdan/argocd-charts.git"
    targetRevision: HEAD 
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
